config/routes.rb
Rails.application.routes.draw do
  root 'combos#index'
  resources :combos
  get '/states/:id/cities', to: 'states#index',  :defaults => { :format => 'json' }
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
end

app/models/combo.rb
class Combo < ActiveRecord::Base
  belongs_to :state
  belongs_to :city
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :set_combo, only: [:show, :edit, :update, :destroy]

  # GET /combos
  # GET /combos.json
  def index
    @combos = Combo.all
  end

  # GET /combos/1
  # GET /combos/1.json
  def show
  end

  # GET /combos/new
  def new
    @combo = Combo.new
  end

  # GET /combos/1/edit
  def edit
  end

  # POST /combos
  # POST /combos.json
  def create
    @combo = Combo.new(combo_params)

    respond_to do |format|
      if @combo.save
        format.html { redirect_to @combo, notice: 'Combo was successfully created.' }
        format.json { render :show, status: :created, location: @combo }
      else
        format.html { render :new }
        format.json { render json: @combo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /combos/1
  # PATCH/PUT /combos/1.json
  def update
    respond_to do |format|
      if @combo.update(combo_params)
        format.html { redirect_to @combo, notice: 'Combo was successfully updated.' }
        format.json { render :show, status: :ok, location: @combo }
      else
        format.html { render :edit }
        format.json { render json: @combo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /combos/1
  # DELETE /combos/1.json
  def destroy
    @combo.destroy
    respond_to do |format|
      format.html { redirect_to combos_url, notice: 'Combo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_combo
      @combo = Combo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def combo_params
      params.require(:combo).permit(:state_id, :city_id)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]
  # GET /states
  # GET /states.json
  def index
    @cities = City.where(state_id: params[:id])
    respond_to do |format|
      format.json  { render :json => @cities.to_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/combos_helper.rb
module CombosHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/combos/_form.html.erb
<%= form_for(@combo) do |f| %>
  <% if @combo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@combo.errors.count, "error") %> prohibited this combo from being saved:</h2>

      <ul>
      <% @combo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state_id %><br>
    <%= f.collection_select :state_id, State.all, :id, :name, prompt: true, hide_label: true %>
  </div>
  <div id="city">
    <select id="combo_city_id" type="text"/></select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript" defer>
$('#combo_state_id').on('change', function() {
  $.getJSON("/states/" + $(this).val() + '/cities.json', function(data) {
    $('#combo_city_id').empty();
    $.each(data, function(i,item){
      $('#combo_city_id').append('<option value="' + item.id + '">' + item.name + '</option>');
    });
  });
});
</script>

app/views/combos/edit.html.erb
<h1>Editing Combo</h1>

<%= render 'form' %>

<%= link_to 'Show', @combo %> |
<%= link_to 'Back', combos_path %>

app/views/combos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Combos</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @combos.each do |combo| %>
      <tr>
        <td><%= combo.state %></td>
        <td><%= combo.city %></td>
        <td><%= link_to 'Show', combo %></td>
        <td><%= link_to 'Edit', edit_combo_path(combo) %></td>
        <td><%= link_to 'Destroy', combo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Combo', new_combo_path %>

app/views/combos/new.html.erb
<h1>New Combo</h1>

<%= render 'form' %>

<%= link_to 'Back', combos_path %>

app/views/combos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @combo.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @combo.city %>
</p>

<%= link_to 'Edit', edit_combo_path(@combo) %> |
<%= link_to 'Back', combos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>